### ISSUE TITLE
Cookie的问题

### ISSUE THREAD

**Issue by AlterGu** [jiegto/Actions_smzdm#1]
SMZDM_COOKIE我这里的跟你readme中的不一样,照做后报错:(node:2715) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
执行完毕
    at Main (/home/runner/work/Actions_smzdm/Actions_smzdm/smzdm_checkin.js:802:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2703) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at resolve (/home/runner/work/Actions_smzdm/Actions_smzdm/sendNotify.js:62:25)
    at new Promise (<anonymous>)
    at serverNotify (/home/runner/work/Actions_smzdm/Actions_smzdm/sendNotify.js:59:13)
    at Object.sendNotify (/home/runner/work/Actions_smzdm/Actions_smzdm/sendNotify.js:53:11)
    at start (/home/runner/work/Actions_smzdm/Actions_smzdm/function/smzdm.js:72:22)
(node:2703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

另外, SMZDM_USER和SMZDM_PASS是登录什么值得买的明文账号和密码吗

**Comment by jiegto** [comment]
1、应该是 cookie 的问题，必须确保是  Cookie 字段从 sess= 开始到结束 的这一段
2、是明文账号密码，具体用到的原因可以查看原脚本作者的说明

我只是单纯做了整合。

**Comment by AlterGu** [comment]
> 1、应该是 cookie 的问题，必须确保是 Cookie 字段从 sess= 开始到结束 的这一段
> 2、是明文账号密码，具体用到的原因可以查看原脚本作者的说明
> 
> 我只是单纯做了整合。

就是说cookie需要包括 'sess=...'而不是仅仅sess=这个等号后面的内容吧, 如果不对请指正.
还有就是如果sess=...;后面有分号接下个内容了的话, 后面的应该不用复制进来了吧

**Comment by jiegto** [comment]
嗯，抱歉，可能是我写得不够清晰。

必须包含 sess= ，另外分号后面，有多少都建议你也一并复制进来。

**Comment by AlterGu** [comment]
> 嗯，抱歉，可能是我写得不够清晰。
> 
> 必须包含 sess= ，另外分号后面，有多少都建议你也一并复制进来。

我按照你说的又重新配置了一遍,然后出现了如下错误:
(node:2558) UnhandledPromiseRejectionWarning: TypeError: desp.replace is not a function
    at resolve (/home/runner/work/Actions_smzdm/Actions_smzdm/sendNotify.js:62:25)
    at new Promise (<anonymous>)
    at serverNotify (/home/runner/work/Actions_smzdm/Actions_smzdm/sendNotify.js:59:13)
    at Object.sendNotify (/home/runner/work/Actions_smzdm/Actions_smzdm/sendNotify.js:53:11)
    at start (/home/runner/work/Actions_smzdm/Actions_smzdm/function/smzdm.js:72:22)
(node:2558) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2558) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
请问这个是什么原因引起的?

**Comment by AlterGu** [comment]
继上个问题,已经排查出了是server酱key的问题, 换成tg推送就好了,但又有了新的问题 : "telegram发送通知消息失败！！"

**Comment by jiegto** [comment]
推送失败，请检查 TG 的 secret 是否填写正确
