### ISSUE TITLE
报错了，不能自动签到了

### ISSUE THREAD

**Issue by zhangdaren** [jiegto/Actions_smzdm#7]
0s
Run node function/smzdm.js

🔔什么值得买签到, 开始!
(node:2494) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.ee.on.res (/home/runner/work/Actions_smzdm_check/Actions_smzdm_check/node_modules/download/node_modules/got/index.js:482:24)
    at EventEmitter.emit (events.js:198:13)
    at getResponse (/home/runner/work/Actions_smzdm_check/Actions_smzdm_check/node_modules/download/node_modules/got/index.js:320:5)
    at Immediate.setImmediate (/home/runner/work/Actions_smzdm_check/Actions_smzdm_check/node_modules/download/node_modules/got/index.js:147:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:2494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlterGu** [comment]
同, 请问怎么解决

**Comment by jiegto** [comment]
上游问题，等修复就好

**Comment by jiegto** [comment]
目前还可以使用，不过个人不准备维护了，建议使用 surge 等App，使用原项目直接使用。
